[X]
;username = @sonyasterik7
;password = jibune21!
;email = sonyasterik7@gmail.com
username = @rafly8081
password = hibarae1399
email = iamnickname19@gmail.com
[GOOGLE]
api_key = AIzaSyD4ijOpz5h3tgwZvuHJml487LqyKmPpvQQ