# Generated by Django 5.1.7 on 2025-06-22 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True, null=True)),
                ('text', models.TextField()),
                ('time', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(blank=True, max_length=255, null=True)),
                ('to_location', models.CharField(blank=True, max_length=255, null=True)),
                ('sentence', models.TextField()),
                ('reason', models.CharField(max_length=255)),
                ('from_lat', models.FloatField(blank=True, null=True)),
                ('from_lng', models.FloatField(blank=True, null=True)),
                ('to_lat', models.FloatField(blank=True, null=True)),
                ('to_lng', models.FloatField(blank=True, null=True)),
                ('single_location', models.CharField(blank=True, max_length=255, null=True)),
                ('single_lat', models.FloatField(blank=True, null=True)),
                ('single_lng', models.FloatField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='traffic.trafficreport')),
            ],
        ),
    ]
