# Generated by Django 5.1.7 on 2025-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficreport',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
