# Generated by Django 5.1.7 on 2025-06-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_alter_trafficreport_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficreport',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
