# Generated by Django 5.1.7 on 2025-06-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_trafficreport_tweet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsegment',
            name='route_polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
