# Generated by Django 5.1.7 on 2025-06-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_trafficsegment_route_polyline'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('count', models.IntegerField(default=0)),
                ('reset_month', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
